
export const data: any[] = [
  {"name":"bulbasaur","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png","type":"grass, poison","id":1},
	{"name":"ivysaur","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png","type":"grass, poison","id":2},
	{"name":"venusaur","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png","type":"grass, poison","id":3},
	{"name":"charmander","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png","type":"fire","id":4},
	{"name":"charmeleon","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png","type":"fire","id":5},
	{"name":"charizard","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png","type":"fire, flying","id":6},
	{"name":"squirtle","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png","type":"water","id":7},
	{"name":"wartortle","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png","type":"water","id":8},
	{"name":"blastoise","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png","type":"water","id":9},
	{"name":"caterpie","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png","type":"bug","id":10},
	{"name":"metapod","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png","type":"bug","id":11},
	{"name":"butterfree","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png","type":"bug, flying","id":12},
	{"name":"weedle","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png","type":"bug, poison","id":13},
	{"name":"kakuna","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png","type":"bug, poison","id":14},
	{"name":"beedrill","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png","type":"bug, poison","id":15},
	{"name":"pidgey","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png","type":"normal, flying","id":16},
	{"name":"pidgeotto","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png","type":"normal, flying","id":17},
	{"name":"pidgeot","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png","type":"normal, flying","id":18},
	{"name":"rattata","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png","type":"normal","id":19},
	{"name":"raticate","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png","type":"normal","id":20},
	{"name":"spearow","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png","type":"normal, flying","id":21},
	{"name":"fearow","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png","type":"normal, flying","id":22},
	{"name":"ekans","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png","type":"poison","id":23},
	{"name":"arbok","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png","type":"poison","id":24},
	{"name":"pikachu","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png","type":"electric","id":25},
	{"name":"raichu","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png","type":"electric","id":26},
	{"name":"sandshrew","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png","type":"ground","id":27},
	{"name":"sandslash","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png","type":"ground","id":28},
	{"name":"nidoran-f","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png","type":"poison","id":29},
	{"name":"nidorina","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png","type":"poison","id":30},
	{"name":"nidoqueen","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png","type":"poison, ground","id":31},
	{"name":"nidoran-m","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png","type":"poison","id":32},
	{"name":"nidorino","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png","type":"poison","id":33},
	{"name":"nidoking","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png","type":"poison, ground","id":34},
	{"name":"clefairy","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png","type":"fairy","id":35},
	{"name":"clefable","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png","type":"fairy","id":36},
	{"name":"vulpix","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png","type":"fire","id":37},
	{"name":"ninetales","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png","type":"fire","id":38},
	{"name":"jigglypuff","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png","type":"normal, fairy","id":39},
	{"name":"wigglytuff","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png","type":"normal, fairy","id":40},
	{"name":"zubat","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png","type":"poison, flying","id":41},
	{"name":"golbat","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png","type":"poison, flying","id":42},
	{"name":"oddish","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png","type":"grass, poison","id":43},
	{"name":"gloom","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png","type":"grass, poison","id":44},
	{"name":"vileplume","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png","type":"grass, poison","id":45},
	{"name":"paras","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png","type":"bug, grass","id":46},
	{"name":"parasect","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png","type":"bug, grass","id":47},
	{"name":"venonat","image":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png","type":"bug, poison","id":48}
]